name: auto build engine

on: 
  release:
    types: [published]
  schedule:
    - cron: "0 16 * * *"
  push:
    branches: 
      - master
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Bulid vlmcsd
      run: |
        git clone https://github.com/Wind4/vlmcsd.git vlmcsdsrc -b master --depth 1
        pushd vlmcsdsrc
        make -j$(nproc)
        popd
        mkdir vlmcsd
        cp vlmcsdsrc/bin/vlmcsd vlmcsd/
        wget --no-check-certificate -O vlmcsd/vlmcsd.service https://raw.githubusercontent.com/Wind4/vlmcsd-debian/master/vlmcsd.service
        sed -i 's/-i \/etc\/vlmcsd\/vlmcsd.ini //' vlmcsd/vlmcsd.service
        
    - name: Upload vlmcsd
      uses: actions/upload-artifact@master
      with:
        name: vlmcsd
        path: vlmcsd

  push:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Clean
      run: |
        rm vlmcsd*
    
    - name: Download vlmcsd
      uses: actions/download-artifact@master
      with:
        name: vlmcsd
        path: ./
    
    - name: Commit
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout --orphan new_branch
        git add -A
        git commit -am "update new file"
        git branch -D master
        git branch -m master
        git push origin master --force
